name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)
    
    - uses: actions/checkout@v2
    - name: Pulls the Docker image
      run: docker pull saprunitin/dockerworker
    
    - uses: actions/checkout@v2
    - name: Runs the Docker image
      run: docker run docker.io/saprunitin/dockerworker:latest
